# Generated by Django 3.2.9 on 2021-12-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default='2021-04-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='organizer_email',
            field=models.EmailField(default='test@test.ru', max_length=254),
            preserve_default=False,
        ),
    ]
